isoapp/urls.py
from django.urls import path
from isoapp import views

urlpatterns = [
    path('', views.login),
    path('signout/', views.signout),
    path('dashboard/', views.dashboard),
    path('user-list/', views.user_list),
    path('user-add/', views.user_add),
    path('gift-card-list/', views.gift_card_list),
    path('gift-card-generate/', views.gift_card_generate),
    path('product-category-list/', views.product_category_list),
    path('product-categroy-add/', views.product_category_add),
    path('product-list/', views.product_list),
    path('product-setup/', views.product_setup),
    path('discount-list/', views.discount_list),
    path('discount-setup/', views.discount_setup),
    path('stock-information/', views.stock_information),
    path('purchase-history/', views.purchase_history),
    path('purchase-product/', views.purchase_product),
    path('sales/', views.sales),
    path('get-gift-card-amount/', views.get_gift_card_amount),
    path('get-discount/', views.get_discount_amount),
    path('convert-amount/', views.convert_amount),
    path('sales-history/', views.sales_history),
    path('invoice-print/<str:invoice_no>/', views.invoice_print),
]

isopos/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "ISHO Pont of Sale Admin"
admin.site.site_title = "ISHO Pont of Sale Admin"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('isoapp.urls')),
    path('/', include('isoapp.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

isoapp/models.py
from django.db import models

# Create your models here.

class UserInfo(models.Model):
    user_name           = models.CharField(max_length = 30, unique = True)
    full_name           = models.CharField(max_length = 50)
    user_img            = models.ImageField(upload_to='user_images', blank=True)
    user_email          = models.CharField(max_length = 100, blank = True, null = True)
    user_mobile         = models.CharField(max_length = 15, blank = True, null = True)
    user_countries = (
        ('Bangladesh', 'Bangladesh'),
        ('USA', 'USA'),
    )
    user_country        = models.CharField(max_length = 50, choices = user_countries)
    user_pass           = models.CharField(max_length = 200)
    address             = models.TextField(blank = True)
    added_by            = models.CharField(max_length = 30)
    status              = models.BooleanField(default = True) 

    def __str__(self):
        return self.user_name

    class Meta:
        verbose_name = "User"
        verbose_name_plural = "User Information" 

class ProductCategory(models.Model):
    category_name    = models.CharField(max_length = 50, unique=True)
    remark       = models.TextField(max_length = 100, blank = True)
    added_by     = models.ForeignKey(UserInfo, on_delete = models.CASCADE)
    status       = models.BooleanField(default = True) 

    def __str__(self):
        return str(self.category_name) 

    class Meta:
        verbose_name = "product category"
        verbose_name_plural = "product category" 

class ProductSetup(models.Model):
    product_name       = models.CharField(max_length = 50)
    category_name    = models.ForeignKey(ProductCategory, on_delete = models.CASCADE)    
    barcode          = models.CharField(max_length = 50, unique=True)
    bdt_unit_price   = models.FloatField(default=0)
    unit_sales_price = models.FloatField(default=0)
    remark           = models.TextField(max_length = 100, blank = True)
    added_by         = models.ForeignKey(UserInfo, on_delete = models.CASCADE)
    added_date       = models.DateTimeField(auto_now_add = True)
    updated_date     = models.DateTimeField(auto_now_add = False, blank = True, null = True)
    status           = models.BooleanField(default = True) 

    def __str__(self):
        return str(self.product_name) 

    class Meta:
        verbose_name = "Product Setup"
        verbose_name_plural = "Product Setup" 

class DiscountSetup(models.Model):
    store_countries = (
        ('Bangladesh', 'Bangladesh'),
        ('USA', 'USA'),
    )
    store_country    = models.CharField(max_length = 50, choices = store_countries)   
    discount_months = (
        ('1', 'January'),
        ('2', 'February'),
        ('3', 'March'),
        ('4', 'April'),
        ('5', 'May'),
        ('6', 'June'),
    )
    discount_month    = models.CharField(max_length = 50, choices = discount_months)   
    discount_parcentage = models.FloatField(default=0)
    start_amount     = models.FloatField(default=0)
    end_amount       = models.FloatField(default=0)
    remark           = models.TextField(max_length = 100, blank = True)
    added_by         = models.ForeignKey(UserInfo, on_delete = models.CASCADE)
    added_date       = models.DateTimeField(auto_now_add = True)
    status           = models.BooleanField(default = True) 

    class Meta:
        verbose_name = "Discount Setup"
        verbose_name_plural = "Discount Setup" 

class GiftCardGenerate(models.Model):   
    card_number      = models.CharField(max_length = 50, unique=True)
    amount           = models.FloatField(default=0)
    remark           = models.TextField(max_length = 100, blank = True)
    added_by         = models.ForeignKey(UserInfo, on_delete = models.CASCADE)
    added_date       = models.DateTimeField(auto_now_add = True)
    status           = models.BooleanField(default = False) 

    def __str__(self):
        return str(self.card_number) 

    class Meta:
        verbose_name = "Gift Card  Generate"
        verbose_name_plural = "Gift Card  Generate" 

class StockInfo(models.Model):
    added_by                = models.ForeignKey(UserInfo, on_delete = models.CASCADE)
    product_name            = models.ForeignKey(ProductSetup, on_delete = models.CASCADE)
    available_quantity      = models.IntegerField(default=0) #Current available Quantity
    stock_quantity          = models.IntegerField(default=0) #Total stock quantity
    update_by               = models.IntegerField(default=0) #update by
    remark                  = models.TextField(max_length = 100, blank = True)
    added_date              = models.DateTimeField(auto_now_add = True)
    updated_date            = models.DateTimeField(auto_now_add = False, blank = True, null = True)
    status                  = models.BooleanField(default = True) 

    def __str__(self):
        return str(self.product_name) 

    class Meta:
        verbose_name = "Stock Information"
        verbose_name_plural = "Stock Information"

class PurchaseHistory(models.Model):
    added_by                = models.ForeignKey(UserInfo, on_delete = models.CASCADE)
    product_name            = models.ForeignKey(ProductSetup, on_delete = models.CASCADE)
    purchase_quantity       = models.IntegerField(default=0) 
    remark                  = models.TextField(max_length = 100, blank = True)
    added_date              = models.DateTimeField(auto_now_add = True)
    status                  = models.BooleanField(default = True) 

    def __str__(self):
        return str(self.product_name) 

    class Meta:
        verbose_name = "Purchase Information"
        verbose_name_plural = "Purchase Information"

class Sales(models.Model):
    invoice_no      = models.CharField(max_length = 30, unique=True)
    added_by        = models.ForeignKey(UserInfo, on_delete = models.CASCADE)
    total_price     = models.FloatField(default=0) 
    vat_amount      = models.FloatField(default=0) 
    discount_amount = models.FloatField(default=0) 
    net_price       = models.FloatField(default=0) 
    paid_amount     = models.FloatField(default=0) 
    remark          = models.TextField(max_length = 500, blank = True)
    added_date      = models.DateTimeField(auto_now_add = True)
    status          = models.BooleanField(default = True) 

    def __str__(self):
        return str(self.invoice_no) 

    class Meta:
        verbose_name = "Sales"
        verbose_name_plural = "Sales"

class SalesHistory(models.Model):
    invoice_no      = models.CharField(max_length = 30)
    added_by        = models.ForeignKey(UserInfo, on_delete = models.CASCADE)
    product_name    = models.ForeignKey(ProductSetup, on_delete = models.CASCADE)
    sales_quantity  = models.IntegerField(default=0) 
    sales_price     = models.FloatField(default=0) 
    total_price     = models.FloatField(default=0) 
    added_date      = models.DateTimeField(auto_now_add = True)
    status          = models.BooleanField(default = True) 

    def __str__(self):
        return str(self.product_name) 

    class Meta:
        verbose_name = "Sales History"
        verbose_name_plural = "Sales History"

isoapp/templates/isoapp/common/discount_list.html
{% extends 'isoapp/common/index.html' %}
{% include "isoapp/common/static_files.html" %}
{% block title %} Discount List{% endblock %}
{% block content %}

<div class="col-10">
    
    <div class="row">
        <div class="col-md-6">
            <strong> <i class="icon-pin"></i> Discount List</strong>
        </div>
        <div class="col-md-6 text-right">
            <a style="text-align: right;" href="/discount-setup/"> <i class="fa fa-plus"></i> Discount Setup</a>
        </div>
    </div>
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}
    <table class="table table-bordered table-stripped">
        <thead>
            <tr>
                <th>SL</th>
                <th>Country</th>
                <th>Discount Month</th>
                <th>Start Amount</th>
                <th>End Amount</th>
                <th>Discount (%)</th>
                <th>Remarks</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            {% for data in discount_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ data.store_country }}</td>
                    <td>{{ data.get_discount_month_display }}</td>
                    <td>{{ data.start_amount }}</td>
                    <td>{{ data.end_amount }}</td>
                    <td>{{ data.discount_parcentage }}</td>
                    <td>{{ data.remark }}</td>
                    <td>{% if data.status == True %} Active {% else %}<strong style="color: red;">Inactive</strong>  {% endif %}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    
</div>
{% endblock %}

isoapp/templates/isoapp/common/discount_setup.html
{% extends 'isoapp/common/index.html' %}
{% include "isoapp/common/static_files.html" %}
{% block title %} Discount Setup{% endblock %}
{% block content %}
<div class="col-10">
    <div class="row">
        <div class="col-md-6">
            <strong> <i class="icon-pin"></i>Discount Setup</strong>
        </div>
        <div class="col-md-6 text-right">
            <a style="text-align: right;" href="/discount-list/"> <i class="fa fa-hand-o-right"></i> Discount List</a>
        </div>
    </div>
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}
    <form method="POST" enctype="multipart/form-data">{% csrf_token %}
        <table class="table table-bordered">
           
            <tr>
                <th>Start Amount<span style="color: red;">*</span>  </th>
                <td> <input type="number" name="start_amount" class="form-control" required /> </td>
            
                <th>End Amount <span style="color: red;">*</span> </th>
                <td> <input type="number" name="end_amount" class="form-control" required /> </td>
            </tr>
            <tr>
                <th>Discount (%) <span style="color: red;">*</span> </th>
                <td> <input type="number" name="discount_parcentage" class="form-control" required /> </td>
                <th>Country <span style="color: red;">*</span> </th>
                <td>
                    <select name="country" class="form-control" required>
                        <option value="">-----Select-----</option>
                        <option value="USA">USA</option>
                        <option value="Bangladesh">Bangladesh</option>
                    </select>
                </td>
            </tr>
            <tr>
                <th>Discount Month <span style="color: red;">*</span> </th>
                <td>
                    <select name="discount_month" class="form-control" required>
                        <option value="">-----Select-----</option>
                        <option value="1">January</option>
                        <option value="2">February</option>
                        <option value="3">March</option>
                        <option value="4">April</option>
                        <option value="5">May</option>
                        <option value="6">June</option>
                    </select>
                </td>
                <th>Remarks</th>
                <td> <textarea type="text" name="remarks" class="form-control" > </textarea> </td>
            </tr>
           
            <tr>
                <td colspan="4" style="text-align: center;"><input type="submit" name="btnSave" value="Save" class="btn btn-success" /></td>
            </tr>
        </table>
    </form>
</div>
{% endblock %}

isoapp/templates/isoapp/common/gift_card_list.html
{% extends 'isoapp/common/index.html' %}
{% include "isoapp/common/static_files.html" %}
{% block title %} Gift Card List{% endblock %}
{% block content %}

<div class="col-10">
    
    <div class="row">
        <div class="col-md-6">
            <strong> <i class="icon-pin"></i> Gift Card List</strong>
        </div>
        <div class="col-md-6 text-right">
            <a style="text-align: right;" href="/gift-card-generate/"> <i class="fa fa-plus"></i> Gift Card Generate</a>
        </div>
    </div>
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}
    <table class="table table-bordered table-stripped">
        <thead>
            <tr>
                <th>SL</th>
                <th>Card Number</th>
                <th>Amount</th>
                <th>Remarks</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            {% for data in gift_card_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ data.card_number }}</td>
                    <td>{{ data.amount }}</td>
                    <td>{{ data.remark }}</td>
                    <td>{% if data.status == True %} <strong style="color: red;">Used</strong> {% else %} Available {% endif %}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    
</div>
{% endblock %}

isoapp/templates/isoapp/common/invoice_print.html
<html>
    <head>
        {% load staticfiles %}
        {% include "isoapp/common/static_files.html" %}
        <title>Invoice</title>
        <style>
            #invoice th {
                background-color:#ddd;       
            }
            @page{
                size:A4 portrait;
                margin:1.2cm;
                
                @frame footer_frame { /* Another static Frame */
                    -pdf-frame-content: footer_content;
                    left: 256pt; width: 512pt; top: 1095px; height: 20pt;
                }
            }
        </style>
    </head>
    
    <body>
    {% for data in service_list %}        
    <div class='wrapper'> 
        <tr>
            <td>Company Logo or Name </td>
        </tr>
   </table>
   <br>
   <table style="padding-left:0px;font-size: 12px;" id="invoice">
        <tr>
            <td colspan="4" style="text-align: left;font-weight:bold;font-size: 14px;">Invoice</td>
        </tr>
        <tr>
            <th>Invoice No :</th>
            <td>{{sales_list.invoice_no}}</td>
            <th>Date :</th>
            <td>{{sales_list.added_date}}</td>
        </tr>
        <tr>
            <td colspan="4">
                <table class="table table-bordered table-stripped">
                    <tr>
                        <th>Product Code</th>
                        <th>Product Name</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Total Price</th>
                    </tr>
                    {% for data in sales_history_list %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{data.product_name__barcode}}</td>
                        <td>{{data.product_name}}</td>
                        <td>{{data.product_name__sales_price}}</td>
                        <td>{{data.sales_quantity}}</td>
                        <td>{{data.total_price}}</td>
                    </tr>
                    {% endfor %}
                </table>
            </td>
        </tr>
        <tr>
            <td colspan="2"></td>
            <th>Payable :</th>
            <td>{{sales_list.total_price}}</td>
        </tr>
        <tr>
            <td colspan="2"></td>
            <th>Vat :</th>
            <td>{{sales_list.vat_amount}}</td>
        </tr>
        <tr>
            <td colspan="2"></td>
            <th>Discount :</th>
            <td>{{sales_list.discount_amount}}</td>
        </tr>
        <tr>
            <td colspan="2"></td>
            <th>Net Amount :</th>
            <td>{{sales_list.net_price}}</td>
        </tr>
        <tr>
            <td colspan="2"></td>
            <th>Paid Amount :</th>
            <td>{{sales_list.paid_amount}}</td>
        </tr>
        <tr>
            <td colspan="2" style="padding-top:5px;">
                Customer Signature: _______________________  
            </td>
            <td colspan="2" style="padding-top:5px;">
                Authorized Signature: _______________________  
            </td>
        </tr>
            <tr>
                <td colspan="4"><p>
                    .....................................................................................................................................................................................................................</p>
                </td>
            </tr>
        </table>

        <table style="margin-top: 20px;">
            <tr>
                <td>Company Logo or Name </td>
            </tr>
       </table>
       <br>
       <table style="padding-left:0px;font-size: 12px;" id="invoice">
            <tr>
                <td colspan="2" style="text-align: left;font-weight:bold;font-size: 14px;">Invoice</td>
            </tr>
            <tr>
                <th>Invoice No :</th>
                <td>{{sales_list.invoice_no}}</td>
                <th>Date :</th>
                <td>{{sales_list.added_date}}</td>
            </tr>
            <tr>
                <td colspan="4">
                    <table class="table table-bordered table-stripped">
                        <tr>
                            <th>Product Code</th>
                            <th>Product Name</th>
                            <th>Price</th>
                            <th>Quantity</th>
                            <th>Total Price</th>
                        </tr>
                        {% for data in sales_history_list %}
                        <tr>
                            <td>{{forloop.counter}}</td>
                            <td>{{data.product_name__barcode}}</td>
                            <td>{{data.product_name}}</td>
                            <td>{{data.product_name__sales_price}}</td>
                            <td>{{data.sales_quantity}}</td>
                            <td>{{data.total_price}}</td>
                        </tr>
                        {% endfor %}
                    </table>
                </td>
            </tr>
            <tr>
                <td colspan="2"></td>
                <th>Payable :</th>
                <td>{{sales_list.total_price}}</td>
            </tr>
            <tr>
                <td colspan="2"></td>
                <th>Vat :</th>
                <td>{{sales_list.vat_amount}}</td>
            </tr>
            <tr>
                <td colspan="2"></td>
                <th>Discount :</th>
                <td>{{sales_list.discount_amount}}</td>
            </tr>
            <tr>
                <td colspan="2"></td>
                <th>Net Amount :</th>
                <td>{{sales_list.net_price}}</td>
            </tr>
            <tr>
                <td colspan="2"></td>
                <th>Paid Amount :</th>
                <td>{{sales_list.paid_amount}}</td>
            </tr>
            <tr>
                <td colspan="2" style="padding-top:5px;">
                    Customer Signature: _______________________  
                </td>
                <td colspan="2" style="padding-top:5px;">
                    Authorized Signature: _______________________  
                </td>
            </tr>
        </table>
    </div>
    {% endfor %}
    </body>
    
</html>

isoapp/templates/isoapp/common/login.html
{% load staticfiles %}
<!doctype html>
<html class="no-js" lang="en">

  <head>
    <title>{% block title %} ISHO POS {% endblock %}</title>
    {% include "isoapp/common/static_files.html" %}
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
    <!--[if lt IE 8]>
		<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
	<![endif]-->
	<div class="error-pagewrap">
		<div class="error-page-int">
			<div class="text-center m-b-md custom-login">
				<h3>PLEASE LOGIN TO ISHO POS</h3>
        <p>This is the best POS</p>
        {% if messages %}
            <div class="messages">
                {% for message in messages %}
                <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
                {% endfor %}
            </div>
        {% endif %}
			</div>
			<div class="content-error">
				<div class="hpanel">
            <div class="panel-body">
                <form action="#" method="POST" id="loginForm">{% csrf_token %}
                    <div class="form-group">
                        <label class="control-label" for="username">Username</label>
                        <input type="text" placeholder="example@gmail.com" title="Please enter you username" required="" value="" name="username" id="username" class="form-control">
                        <span class="help-block small">Your unique username to POS</span>
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="password">Password</label>
                        <input type="password" title="Please enter your password" placeholder="******" required="" value="" name="password" id="password" class="form-control">
                        <span class="help-block small">Yur strong password</span>
                    </div>
                    <button class="btn btn-success ">Login</button>
                </form>
            </div>
        </div>
			</div>
			<div class="text-center login-footer">
				<p>Copyright © 2020. All rights reserved ISHO. </p>
			</div>
		</div>   
    </div>
</body>

</html>

isoapp/templates/isoapp/common/product_category_add.html
{% extends 'isoapp/common/index.html' %}
{% include "isoapp/common/static_files.html" %}
{% block title %} Add Product Category {% endblock %}
{% block content %}
<div class="col-10 reportcard_setting">
    <div class="row">
        <div class="col-md-6">
            <strong> <i class="icon-pin"></i>Add Product Category</strong>
        </div>
        <div class="col-md-6 text-right">
            <a style="text-align: right;" href="/product-category-list/"> <i class="fa fa-hand-o-right"></i>  Product Category List</a>
        </div>
    </div>
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}
    <form method="POST">{% csrf_token %}
        <table class="table table-bordered">
           
            <tr>
                <th>Category Name <span style="color: red;">*</span>  </th>
                <td> <input type="text" name="category_name" class="form-control" required /> </td>
            
                <th>Remarks</th>
                <td> <textarea type="text" name="remarks" class="form-control" > </textarea> </td>
            </tr>
           
            <tr>
                <td colspan="4" style="text-align: center;"><input type="submit" name="btnSave" value="Save" class="btn btn-success" /></td>
            </tr>
        </table>
    </form>
</div>
{% endblock %}

isoapp/templates/isoapp/common/product_category_list.html
{% extends 'isoapp/common/index.html' %}
{% include "isoapp/common/static_files.html" %}
{% block title %} Product Category List {% endblock %}
{% block content %}

<div class="col-10">
    <div class="row">
        <div class="col-md-6">
            <strong> <i class="icon-pin"></i> Product Category List</strong>
        </div>
        <div class="col-md-6 text-right">
            <a style="text-align: right;" href="/product-categroy-add/"> <i class="fa fa-plus"></i> Add Product Category</a>
        </div>
    </div>
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}
    <table class="table table-bordered table-stripped">
        <thead>
            <tr>
                <th>SL</th>
                <th>Category Name</th>
                <th>Remarks</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            {% for data in product_category_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ data.category_name }}</td>
                    <td>{{ data.remark }}</td>
                    <td>{{ data.status }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    
</div>
{% endblock %}

isoapp/templates/isoapp/common/product_list.html
{% extends 'isoapp/common/index.html' %}
{% include "isoapp/common/static_files.html" %}
{% block title %} Product List {% endblock %}
{% block content %}

<div class="col-10">
    <div class="row">
        <div class="col-md-6">
            <strong> <i class="icon-pin"></i> User List</strong>
        </div>
        <div class="col-md-6 text-right">
            <a style="text-align: right;" href="/product-setup/"> <i class="fa fa-plus"></i> Product Setup</a>
        </div>
    </div>
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}
    <table class="table table-bordered table-stripped">
        <thead>
            <tr>
                <th class="text-center">SL</th>
                <th class="text-center">Product Code</th>
                <th>Product Name</th>
                <th>Category</th>
                <th class="text-center">Purchase Price</th>
                <th class="text-center">Sales Price</th>
                <th>Remarks</th>
                <th>Added Date</th>
            </tr>
        </thead>
        <tbody>
            {% for data in product_list %}
                <tr>
                    <td class="text-center">{{ forloop.counter }}</td>
                    <td class="text-center">{{ data.barcode }}</td>
                    <td>{{ data.product_name }}</td>
                    <td>{{ data.category_name }}</td>
                    <td class="text-center">{{ data.bdt_unit_price }}</td>
                    <td class="text-center">{{ data.unit_sales_price }}</td>
                    <td>{{ data.remark }}</td>
                    <td>{{ data.added_date }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    
</div>
{% endblock %}

isoapp/templates/isoapp/common/purchase_product.html
{% extends 'isoapp/common/index.html' %}
{% include "isoapp/common/static_files.html" %}
{% block title %} Purchase Product {% endblock %}
{% block content %}
<div class="col-10 reportcard_setting">
    <div class="row">
        <div class="col-md-6">
            <strong> <i class="icon-pin"></i>Purchase Product</strong>
        </div>
        <div class="col-md-6 text-right">
            <a style="text-align: right;" href="/purchase-history/"> <i class="fa fa-hand-o-right"></i> Purchase History</a>
        </div>
    </div>
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}
    <form method="POST" enctype="multipart/form-data">{% csrf_token %}
        <table class="table table-bordered">
            <tr>
                <th>Category <span style="color: red;">*</span> </th>
                <td>
                    <select name="product_name" id="product_name" class="form-control" required>
                        <option value="">-----Select-----</option>
                        {% for data in product_list %}
                            <option value="{{ data.pk }}">{{ data.product_name }}</option>
                        {% endfor %}
                    </select>
                </td>
                <th>Quantity <span style="color: red;">*</span>  </th>
                <td> <input type="number" name="quantity" class="form-control" required /> </td>
            </tr>
            <tr>
                <th>Remarks</th>
                <td colspan="3"> <textarea type="text" name="remarks" class="form-control" > </textarea> </td>
            </tr>
           
            <tr>
                <td colspan="4" style="text-align: center;"><input type="submit" name="btnSave" value="Save" class="btn btn-success" /></td>
            </tr>
        </table>
    </form>
</div>
{% endblock %}